[workspace]
members = [
    "hartex-discord-core",
    "hartex-discord-entitycache",
    "hartex-discord-eyre",
    "hartex-discord-leader",
    "hartex-discord-worker",
]

[profile.release]
debug = true
