[package]
name = "hartex_gateway"
version = "0.1.0"
edition = "2021"
description = """
The gateway component of the bot.
"""
license = "AGPL-3.0-only"
rust-version = "1.65.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_core = { path = "../hartex-core", features = ["async-runtime", "async-signal", "discord-gateway", "environment", "logging-facilities"] }
hartex_eyre = { path = "../hartex-eyre" }

futures-util = "0.3.24"
lapin = "2.1.1"

[features]
