[package]
name = "interactions"
version = "0.1.0"
edition = "2021"
description = """
Interactions for the bot.
"""
license = "AGPL-3.0-only"
rust-version = "1.62.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base = { path = "../../common/base", features = ["discord-model"] }
