[package]
name = "hartex_discord_rest"
version = "0.1.0"
edition = "2021"
description = """
The REST library for the bot.
"""
license = "AGPL-3.0-only"
rust-version = "1.67.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
