[package]
name = "shell_cli"
version = "0.1.0"
edition = "2021"
description = """
The shell for the Discord bot.
"""
license = "AGPL-3.0-only"
rust-version = "1.62.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shell_cmds = { path = "../cmds" }

nu-ansi-term = "0.45.1"
reedline = "0.5.0"

[[bin]]
name = "shell"
path = "src/main.rs"
