[package]
name = "restreq"
version = "0.1.0"
edition = "2021"
description = """
Convenience functions for building REST requests to the Discord API
"""
license = "AGPL-3.0-only"
rust-version = "1.64.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base = { path = "../../common/base", features = ["discord-http", "discord-model"] }
loadbal = { path = "../loadbal" }
rest = { path = "../rest" }

hyper = { version = "0.14.20", features = ["client", "http1"], default-features = false }
log = "0.4.17"
serde_json = "1.0.82"
