[package]
name = "pg-sess-store"
version = "0.1.0"
edition = "2021"
description = """
An implementation of a PostgreSQL session store for the backend.
"""
license = "AGPL-3.0-only"
rust-version = "1.64.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket.git" }
rocket-session-store = "0.2.0"
