[workspace]
members = [
    "base",
    "cache/base",
    "cache/discord",
    "env",
    "event",
    "ext",
    "gateway",
    "interactions",
    "loadbal",
    "manidb",
    "model",
    "rest",
    "shell/cli",
    "shell/cmds",
]
