[package]
name = "gateway"
version = "0.1.0"
edition = "2021"
description = """
The gateway process for the bot.
"""
license = "AGPL-3.0-only"
rust-version = "1.60.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base = { path = "../base", features = ["discord-gateway", "discord-model", "logging"] }
env = { path = "../env" }
ext = { path = "../ext", features = ["discord-model"] }

futures-util = "0.3.21"
hyper = { version = "0.14.16", features = ["client", "http1"], default-features = false }
log = "0.4.14"
serde_json = "1.0.78"
tokio = { version = "1.16.1", features = ["macros", "rt", "rt-multi-thread"] }
