[package]
name = "gateway"
version = "0.1.0"
edition = "2021"
description = """
The gateway process for the bot.
"""
license = "AGPL-3.0-only"
rust-version = "1.62.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base = { path = "../base", features = ["cmdline", "discord-gateway", "discord-model", "logging", "panicking"] }
env = { path = "../env" }
ext = { path = "../ext", features = ["discord-model-ext"] }

futures-util = "0.3.21"
hyper = { version = "0.14.17", features = ["client", "http1"], default-features = false }
log = "0.4.14"
serde_json = "1.0.79"
tokio = { version = "1.17.0", features = ["macros", "rt", "rt-multi-thread", "sync"] }
