[package]
name = "hartex_discord_commands_manager"
version = "0.1.0"
edition = "2021"
description = """
The commands manager of the bot.
"""
license = "AGPL-3.0-only"
rust-version = "1.68.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_discord_core = { path = "../hartex-discord-core", features = ["environment", "logging-facilities"] }
hartex_discord_eyre = { path = "../hartex-discord-eyre" }

[features]
