[package]
name = "hartex_discord_core"
version = "0.1.0"
edition = "2021"
description = """
The core library of the bot.
"""
license = "AGPL-3.0-only"
rust-version = "1.66.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = { version = "0.15.0", optional = true }
log = { version = "0.4.17", optional = true }
log4rs = { version = "1.2.0", default-features = false, optional = true }
tokio = { version = "1.21.2", optional = true }
twilight-gateway = { git = "https://github.com/twilight-rs/twilight.git", branch = "vilgotf/fix/gateway/heartbeat", optional = true }
twilight-model = { git = "https://github.com/twilight-rs/twilight.git", branch = "vilgotf/fix/gateway/heartbeat", optional = true }

[features]
async-runtime = ["dep:tokio", "tokio?/macros", "tokio?/rt", "tokio?/rt-multi-thread"]
async-signal = ["tokio?/signal"]
discord-gateway = ["dep:twilight-gateway"]
discord-model = ["dep:twilight-model"]
environment = ["dep:dotenv"]
logging-facilities = ["dep:log", "dep:log4rs", "log4rs?/console_appender"]
