[package]
name = "hartex_driver"
version = "1.19.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
hartex_core = { path = "../hartex_core", features = [ "twilight-bundled" ] }
hartex_logging = { path = "../hartex_logging" }
tokio = { version = "1.7.1", features = [ "full" ] }
