[package]
name = "event"
version = "0.1.0"
edition = "2021"
description = """
The event handler process for the bot.
"""
license = "AGPL-3.0-only"
rust-version = "1.60.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base = { path = "../base", features = ["discord-model", "logging"] }
env = { path = "../env" }

log = "0.4.14"
serde_json = "1.0.78"
tide = "0.17.0-beta.1"
tokio = { version = "1.16.1", features = ["macros", "rt", "rt-multi-thread"] }
