[package]
name = "event"
version = "1.28.0"
edition = "2021"
description = """
The event handler process for the bot.
"""
license = "AGPL-3.0-only"
rust-version = "1.60.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base = { path = "../base", features = ["logging"] }
env = { path = "../env" }

hyper = { version = "0.14.16", features = ["http2", "server", "tcp"] }
log = "0.4.14"
tokio = { version = "1.16.1", features = ["macros", "rt", "rt-multi-thread"] }
