[package]
name = "buildsys_configure"
version = "0.1.0"
edition = "2021"
description = """
Pre-make configurator for the bot.
"""
license = "AGPL-3.0-only"
rust-version = "1.64.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "configure"
path = "src/main.rs"
