[package]
name = "hartex_discord_leader"
version = "0.1.0"
edition = "2021"
description = """
The leader component of the bot.
"""
license = "AGPL-3.0-only"
rust-version = "1.67.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_discord_core = { path = "../hartex-discord-core", features = ["async-runtime", "async-signal", "discord-model", "discord-gateway", "environment", "logging-facilities"] }
hartex_discord_eyre = { path = "../hartex-discord-eyre" }

futures-util = "0.3.25"
lapin = "2.1.1"
sqlx = { version = "0.6.2", features = ["postgres", "runtime-tokio-rustls"] }
tracing = { version = "0.1.37", features = ["log-always" ]}

[features]
