[package]
name = "hartex_macros"
version = "1.22.0"
edition = "2021"
description = """
The `hartex_macros` library provides useful macros for the bot.
"""
license = "AGPL-3.0-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
