[package]
name = "driver"
version = "0.1.0"
edition = "2021"
description = """
The main binary for the backend.
"""
license = "AGPL-3.0-only"
rust-version = "1.64.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
model = { path = "../../common/model" }
pg-sess-store = { path = "../pg-sess-store" }
rocket = { git = "https://github.com/SergioBenitez/Rocket.git" }
rocket-session-store = "0.2.0"
