[package]
name = "driver"
version = "0.1.0"
edition = "2021"
description = """
The main binary for the backend.
"""
license = "AGPL-3.0-only"
rust-version = "1.64.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
rocket = { git = "https://github.com/SergioBenitez/Rocket.git" }
