[package]
name = "hartex_buildsystem_driver"
version = "0.1.0"
edition = "2021"
description = """
HarTex buildsystem driver
"""
license = "AGPL-3.0-only"
rust-version = "1.66.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_common_eyre = { path = "../../common/hartex-common-eyre" }

[features]
