[package]
name = "loadbal"
version = "0.1.0"
edition = "2021"
description = """
Load balancer for server backends used by HarTex.
"""
license = "AGPL-3.0-only"
rust-version = "1.61.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "loadbal"
path = "./src/bin/main.rs"

[lib]
name = "loadbal"
crate-type = ["rlib"]
path = "./src/lib/lib.rs"
