[package]
name = "loadbal"
version = "0.1.0"
edition = "2021"
description = """
Load balancer implementation.
"""
license = "AGPL-3.0-only"
rust-version = "1.62.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
