[package]
name = "interactions"
version = "0.1.0"
edition = "2021"
description = """
Interactions for the bot.
"""
license = "AGPL-3.0-only"
rust-version = "1.64.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base = { path = "../base", features = ["discord-model", "discord-util"] }
env = { path = "../env" }
ext = { path = "../ext", features = ["discord-model-ext"] }
restreq = { path = "../restreq" }

clap = { version = "4.0.26", features = ["cargo"] }
hyper = { version = "0.14.23", default-features = false, features = ["client", "http1", "http2", "tcp"] }
log = "0.4.17"
tokio = { version = "1.22.0", features = ["macros", "rt", "rt-multi-thread"] }

[[bin]]
name = "cmdmgmt"
path = "bin/mgmt/main.rs"

[lib]
name = "interactions"
crate-type = ["rlib"]
path = "lib/lib.rs"
