[package]
name = "event"
version = "0.1.0"
edition = "2021"
description = """
The event handler process for the bot.
"""
license = "AGPL-3.0-only"
rust-version = "1.64.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base = { path = "../base", features = ["cmdline", "discord-http", "discord-model", "logging", "panicking"] }
cache_discord = { path = "../cache/discord" }
env = { path = "../env" }
gateway = { path = "../gateway" }
interactions = { path = "../interactions" }
loadbal = { path = "../loadbal" }
manidb = { path = "../manidb" }
rest = { path = "../rest" }
restreq = { path = "../restreq" }

async-tungstenite = { version = "0.18.0", features = ["tokio-runtime"] }
futures-util = "0.3.25"
hyper = { version = "0.14.23", features = ["client", "http1"], default-features = false }
log = "0.4.17"
serde_json = "1.0.88"
tokio = { version = "1.21.2", features = ["macros", "rt", "rt-multi-thread"] }
