[package]
name = "hartex_discord_commands_macros"
version = "0.1.0"
edition = "2021"
description = """
Macros for the command framework.
"""
license = "AGPL-3.0-only"
rust-version = "1.67.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "1.0.103", features = ["full"] }

[features]

[lib]
name = "hartex_discord_commands_macros"
proc-macro = true
