[package]
name = "hartex_discord_entitycache_repositories"
version = "0.1.0"
edition = "2021"
description = """
The repository declarations of the repository cache middleware for HarTex.
"""
license = "AGPL-3.0-only"
rust-version = "1.68.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_discord_entitycache_core = { path = "../hartex-discord-entitycache-core" }

[features]
