[package]
name = "hartex_discord_entitycache"
version = "0.1.0"
edition = "2021"
description = """
The repository cache middleware for HarTex.
"""
license = "AGPL-3.0-only"
rust-version = "1.67.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_discord_core = { path = "../hartex-discord-core", features = ["discord-model"] }
sqlx = { version = "0.6.2", features = [ "postgres", "runtime-tokio-rustls" ], default-features = false }

[features]
