[package]
name = "hartex_macro_utils"
version = "0.1.0"
edition = "2021"
description = """
Macro utilities
"""
license = "AGPL-3.0-only"
rust-version = "1.67.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0.47"
syn = "1.0.105"

[features]
