[package]
name = "hartex_discord_commands_core"
version = "0.1.0"
edition = "2021"
description = """
Core framework for commands.
"""
license = "AGPL-3.0-only"
rust-version = "1.68.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_discord_commands_macros = { optional = true, path = "../hartex-discord-commands-macros" }

[dev-dependencies]
hartex_discord_commands_macros = { path = "../hartex-discord-commands-macros" }

[features]
derive = ["dep:hartex_discord_commands_macros"]
