name: Rust

on:
  push:
    branches: [ infdev ]
  pull_request:
    branches: [ infdev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          profile: default
    - name: Build
      run: cargo build --package hartex --release
