name: Lints

on:
  push:
    branches:
      - nightly
      - stable
  pull_request:
    branches:
      - "**"

env:
  CARGO_TERM_COLOR: always

jobs:
  ClippyCommon:
    name: Clippy (common)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly-2022-07-30
          components: clippy
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run configure
        run: python ./x.py configure
      - name: Run cargo clippy
        run: cd common && cargo clippy --workspace
        env:
          ENABLE_PGSQL_CACHE_BACKEND: false

  RustfmtCommon:
    name: Rustfmt (common)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly-2022-07-30
          components: rustfmt
      - name: Run cargo fmt
        run: cd common && cargo fmt --all -- --check

  ClippyDiscordFrontend:
    name: Clippy (discord-frontend)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly-2022-07-30
          components: clippy
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run configure
        run: python ./x.py configure
      - name: Run cargo clippy
        run: cd discord-frontend && cargo clippy --workspace
        env:
          ENABLE_PGSQL_CACHE_BACKEND: false

  RustfmtDiscordFrontend:
    name: Rustfmt (discord-frontend)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly-2022-07-30
          components: rustfmt
      - name: Run cargo fmt
        run: cd discord-frontend && cargo fmt --all -- --check
