name: Lints

on:
  push:
    branches:
      - nightly
      - stable
  pull_request:
    branches:
      - "**"

env:
  CARGO_TERM_COLOR: always

jobs:
  ClippyDiscordFrontend:
    name: Clippy (discord-frontend)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Run Buildsystem
        run: java -jar ./buildsystem.jar ./build.buildsystem.kts clippy discord-frontend

  RustfmtDiscordFrontend:
    name: Rustfmt (discord-frontend)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
      - name: Run cargo fmt
        run: cd discord-frontend && cargo fmt --all -- --check
