name: Lints

on:
  push:
    branches:
      - nightly
      - stable
  pull_request:
    branches:
      - "**"

env:
  CARGO_TERM_COLOR: always

jobs:
  Clippy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: default
      - name: Obtain Default Build Configuration
        run: curl https://gist.githubusercontent.com/HTG-YT/9f0786e09b7fb7be1e8ea6b50dbeaee2/raw/a3b5c67d3fddc8a3e3be6861995b3ad098d04d83/buildconf.toml > buildconf.toml
      - name: Run cargo clippy
        run: cargo clippy --workspace
        env:
          ENABLE_PGSQL_CACHE_BACKEND: false

  Rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: default
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
        env:
          CFG_IS_STABLE: "false"
          CFG_VERSION_STR: "dummy version str"
