name: Tests

on:
  push:
    branches:
      - nightly
      - stable
  pull_request:
    branches:
      - "**"

jobs:
  BuildDiscordFrontend:
    name: Full Release Build (discord-frontend)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Run Buildsystem
        run: PATH=$HOME/.cargo/bin java -jar ./buildsystem.jar ./build.buildsystem.kts build discord-frontend

  TestDiscordFrontend:
    name: Test (discord-frontend)
    needs:
      - BuildDiscordFrontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-nextest
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run configure
        run: python ./x.py configure
      - name: Test
        run: cd discord-frontend && cargo nextest run
        env:
          ENABLE_PGSQL_CACHE_BACKEND: false
