name: Tests

on:
  push:
    branches:
      - nightly
      - stable
  pull_request:
    branches:
      - "**"

env:
  CARGO_TERM_COLOR: always

jobs:
  Linux:
    name: Linux (Full Build)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: default
      - name: Build
        run: cargo build --release

  macOS:
    name: macOS (Full Build)
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: default
      - name: Build
        run: cargo build --release

  Windows:
    name: Windows (Full Build)
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: default
      - name: Build
        run: cargo build --release

  LinuxConftomlTest:
    name: Linux (Test - hartex_conftoml)
    needs:
      - Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: default
      - name: Test
        run: cargo test

  macOSConftomlTest:
    name: macOS (Test - hartex_conftoml)
    needs:
      - macOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: default
      - name: Test
        run: cargo test

  WindowsConftomlTest:
    name: Windows (Test - hartex_conftoml)
    needs:
      - Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: default
      - name: Test
        run: cargo test