name: Tests

on:
  push:
    branches:
      - nightly
      - stable
  pull_request:
    branches:
      - "**"

env:
  CARGO_TERM_COLOR: always

jobs:
  BuildDiscordFrontend:
    name: Full Release Build (discord-frontend)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Download Buildsystem
        run: curl https://github.com/TeamHarTex/HarTex/releases/tag/buildsystem-2022-11-13/buildsystem.jar --output buildsystem.jar
      - name: Run Buildsystem
        run: chmod +x ./buildsystem.sh && ./buildsystem.sh build discord-frontend

  TestDiscordFrontend:
    name: Test (discord-frontend)
    needs:
      - BuildDiscordFrontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-nextest
      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Download Buildsystem
        run: curl https://github.com/TeamHarTex/HarTex/releases/tag/buildsystem-2022-11-13/buildsystem.jar --output buildsystem.jar
      - name: Run Buildsystem
        run: chmod +x ./buildsystem.sh && ./buildsystem.sh test discord-frontend
