name: Tests (common)

on:
  push:
    branches:
      - nightly
      - stable
  pull_request:
    branches:
      - "**"

env:
  CARGO_TERM_COLOR: always

jobs:
  Build:
    name: Full Release Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: default
      - uses: actions/setup-python@v4
      - name: Install Python 3.10
        with:
          python-version: '3.10'
      - name: Run configure
        run: python ./x.py configure
      - name: Build
        run: cd common && cargo build --release
        env:
          ENABLE_PGSQL_CACHE_BACKEND: false

  Test:
    name: Test
    needs:
      - Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: default
      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-nextest
      - uses: actions/setup-python@v4
      - name: Install Python 3.10
        with:
          python-version: '3.10'
      - name: Run configure
        run: python ./x.py configure
      - name: Test
        run: cd common && cargo nextest run
        env:
          ENABLE_PGSQL_CACHE_BACKEND: false
