name: Tests

on:
  push:
    branches:
      - nightly
      - stable
  pull_request:
    branches:
      - "**"

env:
  CARGO_TERM_COLOR: always

jobs:
  Build:
    name: Full Release Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: default
      - name: Obtain Default Build Configuration
        run: curl https://gist.githubusercontent.com/HTG-YT/9f0786e09b7fb7be1e8ea6b50dbeaee2/raw/a353e5c6f927ad63b9ebeae09a44b5e4c4955b0b/buildconf.toml > buildconf.toml
      - name: Build
        run: cargo build --release
        env:
          ENABLE_PGSQL_CACHE_BACKEND: false

  Test:
    name: Test
    needs:
      - Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: default
      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-nextest
      - name: Obtain Default Build Configuration
        run: curl https://gist.githubusercontent.com/HTG-YT/9f0786e09b7fb7be1e8ea6b50dbeaee2/raw/a353e5c6f927ad63b9ebeae09a44b5e4c4955b0b/buildconf.toml > buildconf.toml
      - name: Test
        run: cargo nextest run
        env:
          ENABLE_PGSQL_CACHE_BACKEND: false
