name: Tests

on:
  push:
    branches:
      - nightly
      - stable
  pull_request:
    branches:
      - "**"

env:
  CARGO_TERM_COLOR: always

jobs:
  Build:
    name: Full Release Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: default
      - name: Obtain Default Build Configuration
        run: curl https://gist.githubusercontent.com/HTG-YT/9f0786e09b7fb7be1e8ea6b50dbeaee2/raw/a3b5c67d3fddc8a3e3be6861995b3ad098d04d83/buildconf.toml > buildconf.toml
      - name: Build
        run: cargo build --release
        env:
          ENABLE_PGSQL_CACHE_BACKEND: false

  Test:
    name: Test
    needs:
      - Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: default
      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-nextest
      - name: Obtain Default Build Configuration
        run: curl https://gist.githubusercontent.com/HTG-YT/9f0786e09b7fb7be1e8ea6b50dbeaee2/raw/a3b5c67d3fddc8a3e3be6861995b3ad098d04d83/buildconf.toml > buildconf.toml
      - name: Test
        run: cargo nextest
        env:
          ENABLE_PGSQL_CACHE_BACKEND: false
